name: con
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.11.9
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.15.4
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.24.4
      - packaging==24.1
      - pillow==10.4.0
      - pyparsing==3.1.2
      - sympy==1.13.1
      - torch==2.4.0
      - torchvision==0.19.0
      - tqdm==4.66.4
      - typing-extensions==4.12.2
